import Layout from "@/components/Layout";
import { AllPages } from "@/utils/types/enums";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout page={AllPages.LOGIN}>Login</Layout>
    </>
  );
}
